### PR TITLE
Timing and rpcauth

### PR DESCRIPTION
**Pull request by ziggie1984**
This is hopefully the final change I have to make to use satstack on the raspiblitz.

1. It changes the README to use rpcauth in the bitcoin.conf instead of the normal rpcuser/rpcpassword

2. It adds a new config file `lss_rescan.json` which will remember the latest block this wallet was synced. Every time the user ends the program, the current state is dumped into the file leading to way fewer loading times, making this whole project more userfriendly.

### CODE REVIEW

**Comment by ziggie1984** [comment]
This PR builds on the previous change, sothat I could test it way more easily, in case the other change is merged, I will rebase this change.

**Comment by ziggie1984** [comment]
The lss_rescan.json has the following information and will reside in the same dir as the lss.json:

```
{
 "last_synctime": "Thu Dec 22 18:49:10 2022",
 "timestamp": "1671731350",
 "last_block": 768516,
 "satstack_version": "v0.16.1"
}
```

**Comment by ziggie1984** [comment]
Fixes #91 #90 #86 and many more, I did not search through all of them

**Comment by ziggie1984** [comment]
If you want to scan the wallet from a specific block, just edit the lss_rescan.json and paste the lastblock you want to rescan from.

**Review by adrienlacombe-ledger — APPROVED** [review]

**Pull request merged**
